function [] = run_submovement_decomposition(datafile, output_file, varargin)

defaults = { ...
    'proc_idx', 1, ...
    'n_procs', 1 ...
    'method', 'scattershot', ...
    'opt_vars', 'shape', ...
};

proc_idx = get_var('proc_idx', 'defaults', defaults, varargin{:});
n_procs = get_var('n_procs', 'defaults', defaults, varargin{:});
method = get_var('method', 'defaults', defaults, varargin{:});

load(datafile)
[movements, submovement_recon, segments, costs] = decompose_submovements_v2(hand_kin, ...
    varargin{:});
save(output_file)
end